### PR TITLE
Feature/#17 Create equipment field

### PR DESCRIPTION
**Pull request by MangriMen**

### CODE REVIEW

**Comment by MangriMen** [comment]
[Create equipment field](https://trello.com/c/n8fNRJ2f/17-create-equipment-field)

**Review by StepanovRoma — APPROVED** [review]

**Comment by MangriMen** [comment]
image

**Review by FFreestyler — APPROVED** [review]

**Comment by MangriMen** [comment]
image

**Comment by MangriMen** [comment]
1 or 2
1
image
2
image

**Review by StepanovRoma — APPROVED** [review]

**Comment by FFreestyler** [comment]
1
🥺

**Comment by IHiFiveI** [comment]
2
🥺

**Comment by StepanovRoma** [comment]
1

**Pull request merged**
